// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA89rddkyhlfQW4MT_LdwSQP1nZ33AvRoI',
    appId: '1:270386460289:web:5c99590e1da709839a7f80',
    messagingSenderId: '270386460289',
    projectId: 'edupet-vn-khkt',
    authDomain: 'edupet-vn-khkt.firebaseapp.com',
    storageBucket: 'edupet-vn-khkt.firebasestorage.app',
    measurementId: 'G-MVN11NDD63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FXOz75ZAa9PFWeQbItm62kg5WTnOY7o',
    appId: '1:270386460289:android:9c85160b5c2dea3e9a7f80',
    messagingSenderId: '270386460289',
    projectId: 'edupet-vn-khkt',
    storageBucket: 'edupet-vn-khkt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGeMJ8gDdBAK3VpOkr4I7G1aP1K5q9yE',
    appId: '1:270386460289:ios:58531a374dbd4b529a7f80',
    messagingSenderId: '270386460289',
    projectId: 'edupet-vn-khkt',
    storageBucket: 'edupet-vn-khkt.firebasestorage.app',
    iosBundleId: 'com.example.edupet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXGeMJ8gDdBAK3VpOkr4I7G1aP1K5q9yE',
    appId: '1:270386460289:ios:ef12cb7e94a91ffd9a7f80',
    messagingSenderId: '270386460289',
    projectId: 'edupet-vn-khkt',
    storageBucket: 'edupet-vn-khkt.firebasestorage.app',
    iosBundleId: 'com.edupet.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA89rddkyhlfQW4MT_LdwSQP1nZ33AvRoI',
    appId: '1:270386460289:web:76c4b4ddd418732c9a7f80',
    messagingSenderId: '270386460289',
    projectId: 'edupet-vn-khkt',
    authDomain: 'edupet-vn-khkt.firebaseapp.com',
    storageBucket: 'edupet-vn-khkt.firebasestorage.app',
    measurementId: 'G-S2313CR9PT',
  );
}
